# Generated by Django 3.0 on 2020-01-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='facultysignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('designation', models.CharField(max_length=20)),
                ('joiningdate', models.DateField(max_length=10)),
                ('qualification', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(max_length=20)),
                ('batch', models.CharField(max_length=20)),
                ('blood', models.CharField(blank=True, max_length=20)),
                ('dob', models.DateField(max_length=10)),
                ('address', models.CharField(blank=True, max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
